Enhancing the contributing.md document
jupyter-widgets/ipywidgets pull request #3326
Opened 2021-12-15 22:44 UTC by real-slim-chadi

Hello guys,

Here is my first PR. I am happy to work on better documentation for contributors!

Better Documentation=Easier Development
---------

I have a couple of suggestions
# Suggestions:
## Add a td;lr on each link
    - So that the new participant doesn't feel intimidated by the sheer amount of reading to do
## Add a "to reach out" section
    - with added contact info (if a contributor prefers a different messaging channel together with GitHub)

--------------
Here are some of my comments (having a fresh eye)
# Comments
## Community guidelines:
**Jupyter Guidelines link is broken**
- We can directly link to IPython Guidelines
    - This way, the new person has one link to click

## Current developer information
  - Give a more descriptive title
    - Example: "ipywidgets: what it is"

## Developer install information
  - steps are clear, concise and precise
  - Put the setup and [troubleshooting, updating] in the Main contribute file
    - "For more info refer to the guidelines"
    - **testing contributions is in the install information**
## release procedures
  - put the Header 2s as a td;lr
## testing
  - Concise
  - put Header 2s as td;lr
## Documentation
  - Also, Concise
  - put Header 2's as td'lr

2021-12-17 18:45 UTC, ohrely commented
@ibdafna can you please approve the workflows?  @real-slim-chadi and I aren't permissioned for it.

2022-01-12 05:45 UTC, ibdafna requested changes

2022-01-12 05:45 UTC, ibdafna commented on CONTRIBUTING.md
> +- issues are managed by the `@meeseeksdev` bot
Would it be possible to remove this line?

2022-01-12 05:45 UTC, ibdafna commented on CONTRIBUTING.md
> +Now that we went through the basics, Here are more detailed documentation on areas of contribution:
```suggestion
Now that we went through the basics, here is more detailed documentation on areas of contribution:
```

2022-01-12 05:46 UTC, ibdafna commented
@real-slim-chadi many thanks for the contribution! 😸

2022-01-18 23:11 UTC, merged